const types = {
  UPDATE_CREATE_CHARACTER: "UPDATE_CREATE_CHARACTER",
  RESET_CREATE_CHARACTER: "RESET_CREATE_CHARACTER",
  CREATE_CHARACTER_START: "CREATE_CHARACTER_START",
  CREATE_CHARACTER_SUCCESS: "CREATE_CHARACTER_SUCCESS",
  CREATE_CHARACTER_FAILURE: "CREATE_CHARACTER_FAILURE",
};

export default types;
