const types = {
  GET_GAME_START: "GET_GAME_START",
  GET_GAME_SUCCESS: "GET_GAME_SUCCESS",
  GET_GAME_FAILURE: "GET_GAME_FAILURE",
  UPDATE_GAME_CHARACTER: "UPDATE_GAME_CHARACTER",
};

export default types;
