const types = {
  GET_USER_CHARACTERS_START: "GET_USER_CHARACTERS_START",
  GET_USER_CHARACTERS_SUCCESS: "GET_USER_CHARACTERS_SUCCESS",
  GET_USER_CHARACTERS_FAILURE: "GET_USER_CHARACTERS_FAILURE",
};

export default types;
