const types = {
  GET_USER_CHARACTERS_START: "GET_USER_CHARACTERS_START",
  GET_USER_CHARACTERS_SUCCESS: "GET_USER_CHARACTERS_SUCCESS",
  GET_USER_CHARACTERS_FAILURE: "GET_USER_CHARACTERS_FAILURE",
  DELETE_USER_CHARACTER_START: "DELETE_USER_CHARACTER_START",
  DELETE_USER_CHARACTER_SUCCESS: "DELETE_USER_CHARACTER_SUCCESS",
  DELETE_USER_CHARACTER_FAILURE: "DELETE_USER_CHARACTER_FAILURE",
};

export default types;
