const types = {
  UPDATE_USER_CHARACTER: "UPDATE_USER_CHARACTER",
  RESET_USER_CHARACTER: "RESET_USER_CHARACTER",
  GET_USER_CHARACTER_START: "GET_USER_CHARACTER_START",
  GET_USER_CHARACTER_SUCCESS: "GET_USER_CHARACTER_SUCCESS",
  GET_USER_CHARACTER_FAILURE: "GET_USER_CHARACTERS_FAILURE",
  CREATE_CHARACTER_START: "CREATE_CHARACTER_START",
  CREATE_CHARACTER_SUCCESS: "CREATE_CHARACTER_SUCCESS",
  CREATE_CHARACTER_FAILURE: "CREATE_CHARACTERS_FAILURE",
  UPDATE_USER_CHARACTER_START: "UPDATE_USER_CHARACTER_START",
  UPDATE_USER_CHARACTER_SUCCESS: "UPDATE_USER_CHARACTER_SUCCESS",
  UPDATE_USER_CHARACTER_FAILURE: "UPDATE_USER_CHARACTERS_FAILURE",
};

export default types;
