const types = {
  GET_USER_CHARACTER_START: "GET_USER_CHARACTER_START",
  GET_USER_CHARACTER_SUCCESS: "GET_USER_CHARACTER_SUCCESS",
  GET_USER_CHARACTER_FAILURE: "GET_USER_CHARACTERS_FAILURE",
};

export default types;
