const types = {
  UPDATE_USER_CHARACTER: "UPDATE_USER_CHARACTER",
  RESET_USER_CHARACTER: "RESET_USER_CHARACTER",
  GET_USER_CHARACTER_START: "GET_USER_CHARACTER_START",
  GET_USER_CHARACTER_SUCCESS: "GET_USER_CHARACTER_SUCCESS",
  GET_USER_CHARACTER_FAILURE: "GET_USER_CHARACTER_FAILURE",
  CREATE_USER_CHARACTER_START: "CREATE_USER_CHARACTER_START",
  CREATE_USER_CHARACTER_SUCCESS: "CREATE_USER_CHARACTER_SUCCESS",
  CREATE_USER_CHARACTER_FAILURE: "CREATE_USER_CHARACTER_FAILURE",
  UPDATE_USER_CHARACTER_START: "UPDATE_USER_CHARACTER_START_START",
  UPDATE_USER_CHARACTER_SUCCESS: "UPDATE_USER_CHARACTER_SUCCESS",
  UPDATE_USER_CHARACTER_FAILURE: "UPDATE_USER_CHARACTER_FAILURE",
  SET_USER_CHARACTER: "SET_USER_CHARACTER",
};

export default types;
